version: '3.7'

services:
  frontend:
    image: ghcr.io/mvoreichental/pictureuploader
    build: .
    volumes:
      - albums:/albums
      - queue:/queue
      - /data/pictures/Vereine/Musikverein:/pictures:ro
    ports:
      - target: 80
        published: 80
    command: frontend

  backend:
    image: ghcr.io/mvoreichental/pictureuploader
    build: .
    volumes:
      - albums:/albums
      - queue:/queue
      - pictures-cache:/pictures-cache
      - /data/pictures/Vereine/Musikverein:/pictures:ro
    command: backend

volumes:
  albums:
  queue:
  pictures-cache: